### ISSUE TITLE
Add slack app and slack link checker bot

### ISSUE THREAD

**Issue by ayumi-cloud** [WhichBrowser/Parser-PHP#490]
### Slack app

Example:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) AtomShell/2.3.1 Chrome/52.0.2743.82 Electron/1.3.8 Safari/537.36 Slack_SSB/2.3.1
```

Gives the following results:

```
Browser Name: 'Slack Browser',
Browser Version: '2.3.1'
```

See PR: https://github.com/WhichBrowser/Parser-PHP/pull/379

### Slackbot Link Checker

Example:

```
Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)
Slackbot-LinkExpanding (+https://api.slack.com/robots)
```

Gives the following:

```
browser:
    name: 'Slackbot Link Checker'
    version: '1.0'
device:
    type: bot
```

See PR: https://github.com/WhichBrowser/Parser-PHP/pull/490
